# Generated by Django 4.2.7 on 2023-12-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_payment', '0001_initial'),
        ('app_pwl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pwl.course', verbose_name='Course for payment'),
        ),
        migrations.AddField(
            model_name='stripesession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pwl.lesson', verbose_name='Lesson for payment'),
        ),
    ]
